name: deploy
on:
  push:
    branches:
      - production
jobs:
  to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "monorepo-chatapp"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
