name: CI/CD
on:
  pull_request:
    branch:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
          POSTGRES_DB: mydb
          TZ: Asia/Tokyo
        ports:
          - 5432:5432
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: yarn install
      - name: Run Server test
        run: yarn run server:test
